"""Static Catalog export (R-platform P1, read-only path).

The owner's split: *viewing* defined tasks + reports needs no server — only
*defining/editing* tasks needs the FastAPI control plane. This module renders a
self-contained, read-only **Catalog** (category->service drilldown + focused
dependency graph) from the resource-task model, for GitHub Pages / the
`/platform/` static bundle. The composer stays the single source of truth: the
per-node focus graphs are precomputed with :func:`composer.focus_view`.

    python -m controlplane.graph_export <outdir>     # writes catalog.html + data

No fastapi/network needed (composer is pure). Edits link back to the live
control plane at /planning/resources/<id>.
"""
from __future__ import annotations

import json
import shutil
import sys
from pathlib import Path

from regression.scenarios import composer

HERE = Path(__file__).resolve().parent


def _requires_summary(task: dict) -> dict:
    and_deps, groups, creds = composer._norm_requires(task or {})
    return {
        "and": [{"ref": d["ref"], "count": d["count"]} for d in and_deps],
        "one_of": [{"bind": g.get("bind"), "branches": [b["ref"] for b in g["branches"]]}
                   for g in groups],
        "creds": creds,
    }


def build_catalog(model: dict | None = None) -> dict:
    if model is None:
        model = composer.load_model()
    groups_meta = composer.__dict__.get("load_groups")  # not present; load file
    groups = {}
    gpath = Path(composer.DEFAULT_MODEL_DIR) / "_groups.yaml"
    if gpath.exists():
        import yaml
        groups = (yaml.safe_load(gpath.read_text()) or {}).get("groups", {}) or {}

    # reverse index for dependents (one scan)
    dep_index: dict[str, list] = {nid: [] for nid in model}
    for nid, task in model.items():
        and_deps, gps, _ = composer._norm_requires(task or {})
        refs = {d["ref"] for d in and_deps}
        for g in gps:
            refs.update(b["ref"] for b in g["branches"])
        for r in refs:
            if r in dep_index:
                dep_index[r].append(nid)

    nodes, focus = {}, {}
    for nid, task in sorted(model.items()):
        task = task or {}
        service = task.get("service", "")
        cat = service.split("/")[0] if "/" in service else ""
        code = task.get("code") or ""
        group = task.get("group") or ("-".join(code.split("-")[:2]) if code else cat)
        create = task.get("create") or {}
        opts = []
        for oname, ospec in (create.get("options") or {}).items():
            if isinstance(ospec, dict):
                opts.append({"name": oname, "type": ospec.get("type", "?"),
                             "required": bool(ospec.get("required", False)),
                             "values": ospec.get("values")})
            else:
                opts.append({"name": oname, "type": "?", "required": False})
        nodes[nid] = {
            "id": nid, "code": code, "service": service, "category": cat,
            "group": group,
            "group_label": (groups.get(group) or {}).get("label", group),
            "provenance": task.get("provenance", "?"),
            "heavy": bool(task.get("heavy", False)),
            "quota": task.get("quota"),
            "endpoint": create.get("endpoint", ""),
            "requires": _requires_summary(task),
            "options": opts,
            "dependents": sorted(dep_index.get(nid, [])),
            "verify_n": len(task.get("verify") or []),
        }
        try:
            focus[nid] = composer.focus_view(nid, model=model)
        except Exception as exc:  # never let one bad node fail the export
            focus[nid] = {"error": str(exc), "nodes": [], "edges": [], "focus": nid}

    val = sum(1 for n in nodes.values() if n["provenance"] == "VALIDATED")
    return {
        "generated_from": "knowledge/formal/resources/*.yaml (via composer)",
        "node_count": len(nodes), "validated": val,
        "groups": {g: {"label": (groups.get(g) or {}).get("label", g),
                       "category": (groups.get(g) or {}).get("category", "")}
                   for g in sorted({n["group"] for n in nodes.values()})},
        "nodes": nodes, "focus": focus,
    }


def export(outdir: str | Path) -> Path:
    out = Path(outdir)
    out.mkdir(parents=True, exist_ok=True)
    data = build_catalog()
    (out / "catalog.js").write_text(
        "// AUTO-GENERATED by controlplane/graph_export.py\n"
        "window.CATALOG = " + json.dumps(data, ensure_ascii=False) + ";\n",
        encoding="utf-8")
    shutil.copyfile(HERE / "static" / "graph.js", out / "graph.js")
    (out / "catalog.html").write_text(_CATALOG_HTML, encoding="utf-8")
    (out / ".nojekyll").write_text("", encoding="utf-8")
    print(f"wrote {out}/catalog.html — {data['node_count']} nodes, "
          f"{data['validated']} VALIDATED, {len(data['groups'])} groups")
    return out / "catalog.html"


_CATALOG_HTML = r"""<!doctype html><html lang="ko"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>자원 카탈로그 (읽기 전용)</title>
<style>
:root{--bg:#0f1720;--panel:#16212e;--panel2:#1c2a3a;--line:#27384b;--ink:#e7eef6;
  --muted:#90a4ba;--accent:#5aa9ff;--val:#3fb27f;--docs:#e0922f}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);
  font:14px/1.5 ui-sans-serif,-apple-system,Segoe UI,"Noto Sans KR",sans-serif}
a{color:var(--accent);text-decoration:none}.wrap{max-width:1280px;margin:0 auto;padding:20px}
h1{font-size:18px}.muted{color:var(--muted)}code{font-family:ui-monospace,Consolas,monospace}
.cols{display:grid;grid-template-columns:280px 1fr 300px;gap:16px;align-items:start}
@media(max-width:1050px){.cols{grid-template-columns:1fr}}
.panel{background:var(--panel);border:1px solid var(--line);border-radius:12px;padding:14px}
.panel h2{font-size:14px;margin:0 0 10px}.panel h3{font-size:12px;color:var(--muted);
  text-transform:uppercase;letter-spacing:.5px;margin:14px 0 6px}
select,input{width:100%;background:var(--panel2);border:1px solid var(--line);color:var(--ink);
  border-radius:8px;padding:6px 9px;font-size:13px;margin-bottom:8px}
.chk{display:flex;align-items:center;gap:7px;padding:3px 4px;border-radius:6px;cursor:pointer}
.chk:hover{background:var(--panel2)}.chk .dot{width:8px;height:8px;border-radius:50%}
.scroll{max-height:520px;overflow:auto}.svgbox{background:#0f1720;border:1px solid var(--line);
  border-radius:10px;overflow:auto}.legend{display:flex;gap:12px;flex-wrap:wrap;font-size:12px;
  color:var(--muted);margin:6px 0}.legend i{display:inline-block;width:11px;height:11px;border-radius:3px}
.chip{display:inline-block;background:var(--panel2);border:1px solid var(--line);border-radius:14px;
  padding:2px 8px;font-size:11.5px;margin:2px}.kv{display:flex;justify-content:space-between;
  padding:3px 0;border-bottom:1px dashed var(--line)}.tbl{width:100%;border-collapse:collapse;font-size:12px}
.tbl td,.tbl th{text-align:left;padding:4px 6px;border-bottom:1px solid var(--line)}
.note{background:var(--panel2);border-left:3px solid var(--accent);border-radius:6px;padding:9px 12px;
  color:var(--muted);font-size:12.5px;margin-top:10px}.foot{margin-top:30px;color:#6b7e93;font-size:12px}
</style></head><body><div class="wrap">
<h1>자원 카탈로그 <span class="muted" style="font-size:13px">— 읽기 전용 (정적). 정의/수정은 control plane에서.</span></h1>
<p class="muted" id="sub"></p>
<div class="cols">
  <div class="panel">
    <h2>서비스 선택</h2>
    <label>카테고리<select id="cat"></select></label>
    <label>서비스<select id="svc"></select></label>
    <h3>자원 노드</h3><div class="scroll" id="list"></div>
  </div>
  <div class="panel">
    <h2 id="gtitle"></h2>
    <div class="legend"><span><i style="background:var(--val)"></i>VALIDATED</span>
      <span><i style="background:var(--docs)"></i>docs</span>
      <span><i style="background:#5aa9ff"></i>초점 ★</span>
      <span><i style="background:#b48cff"></i>피의존 ↓</span></div>
    <div class="svgbox"><svg id="svg"></svg></div>
    <p class="muted" id="ghint" style="font-size:12px"></p>
  </div>
  <div class="panel" id="detail"></div>
</div>
<div class="foot">생성: <span id="gen"></span> · composer.focus_view 미리계산. 편집은
  <code>/planning/resources/&lt;id&gt;</code>(FastAPI).</div>
</div>
<script src="catalog.js"></script><script src="graph.js"></script>
<script>
var C=window.CATALOG,N=C.nodes,sel=null;
document.getElementById("sub").textContent=C.node_count+" 노드 · "+C.validated+" VALIDATED · "+Object.keys(C.groups).length+" 그룹";
document.getElementById("gen").textContent=C.generated_from;
var cats=[...new Set(Object.values(N).map(n=>n.category))].sort();
var svcOf={};Object.values(N).forEach(n=>{(svcOf[n.category]=svcOf[n.category]||new Set()).add(n.service);});
function fill(s,arr,v){s.innerHTML=arr.map(x=>'<option '+(x===v?'selected':'')+'>'+x+'</option>').join("");}
function pickFirst(){sel="vpc" in N?"vpc":Object.keys(N)[0];}
pickFirst();
function refresh(){
  var n=N[sel];fill(document.getElementById("cat"),cats,n.category);
  fill(document.getElementById("svc"),[...svcOf[n.category]].sort(),n.service);
  var ids=Object.keys(N).filter(id=>N[id].service===n.service).sort();
  document.getElementById("list").innerHTML=ids.map(id=>'<label class="chk"><input type="radio" name="nd" '+(id===sel?"checked":"")+' data-id="'+id+'"><span class="dot" style="background:'+(N[id].provenance==="VALIDATED"?"#3fb27f":"#e0922f")+'"></span><b>'+id+'</b> <span class="muted" style="font-size:11px">'+(N[id].requires.and.length+N[id].requires.one_of.length)+"↑ "+N[id].dependents.length+"↓</span></label>").join("");
  document.querySelectorAll('#list input').forEach(r=>r.onchange=function(){sel=r.dataset.id;refresh();});
  // graph
  var g=C.focus[sel];
  document.getElementById("gtitle").innerHTML="<code>"+sel+"</code> 의존 관계";
  document.getElementById("ghint").textContent="왼쪽=의존(선행), 오른쪽=피의존(후행). 노드 클릭=초점 이동.";
  if(g&&!g.error)ResourceGraph.render(document.getElementById("svg"),g,{onClick:function(id){if(N[id]){sel=id;refresh();}}});
  else document.getElementById("svg").innerHTML='<text x="12" y="24" fill="#ff8585">'+(g&&g.error||"no graph")+'</text>';
  // detail
  var req=n.requires,reqHtml=req.and.map(d=>'<span class="chip">'+d.ref+(d.count>1?" ×"+d.count:"")+'</span>').join("")+req.one_of.map(o=>'<span class="chip">🔀 '+o.branches.join(" | ")+'</span>').join("")||'<span class="muted">없음</span>';
  var depHtml=n.dependents.length?n.dependents.map(d=>'<span class="chip">'+d+'</span>').join(""):'<span class="muted">없음</span>';
  var optHtml=n.options.length?'<table class="tbl">'+n.options.map(o=>'<tr><td><code>'+o.name+'</code></td><td class="muted">'+o.type+(o.required?" *":"")+'</td></tr>').join("")+'</table>':'<p class="muted">옵션 없음</p>';
  document.getElementById("detail").innerHTML='<h2>'+sel+'</h2>'+
    '<div class="kv"><span>service</span><b>'+n.service+'</b></div>'+
    '<div class="kv"><span>provenance</span><b style="color:'+(n.provenance==="VALIDATED"?"#3fb27f":"#e0922f")+'">'+n.provenance+'</b></div>'+
    '<div class="kv"><span>endpoint</span><b style="font-size:11px">'+(n.endpoint||"—")+'</b></div>'+
    (n.quota?'<div class="kv"><span>quota</span><b>⛔ '+n.quota+'</b></div>':'')+
    '<h3>requires</h3><div>'+reqHtml+'</div>'+
    '<h3>피의존</h3><div>'+depHtml+'</div>'+
    '<h3>options</h3>'+optHtml+
    '<div class="note">이 화면은 읽기 전용입니다. 정의/수정은 control plane <code>/planning/resources/'+sel+'</code> 에서.</div>';
}
document.getElementById("cat").onchange=function(e){var c=e.target.value;var fs=[...svcOf[c]].sort()[0];sel=Object.keys(N).find(id=>N[id].service===fs);refresh();};
document.getElementById("svc").onchange=function(e){var s=e.target.value;sel=Object.keys(N).find(id=>N[id].service===s);refresh();};
refresh();
</script></body></html>"""


if __name__ == "__main__":
    out = sys.argv[1] if len(sys.argv) > 1 else "reports/catalog-static"
    export(out)
