"""RETIRED — duplicate `platform/*` static export (IA.md migration WS V5).

This module used to render the FastAPI read-only views (Planning/coverage) via
TestClient and publish them to GitHub Pages under `/platform/`. That surface
DUPLICATED the canonical platform static read face now generated by
`controlplane/graph_export.py` -> `catalog/` (catalog · plan · run · report).

Per docs/IA.md (v2, two-tier IA, WS V5) the `platform/*` export is retired: the
CI publish job (`.github/workflows/api-test.yml`) no longer builds
`reports/platform-static` or copies it to `dashboard-data/platform/`. Nothing
imports this module; it is kept only as a discoverable deprecation breadcrumb.
"""
from __future__ import annotations

import sys

_MSG = (
    "static_export is retired; the canonical platform static face is "
    "controlplane/graph_export.py -> catalog/ (see docs/IA.md)"
)


def main(argv=None) -> int:
    print(_MSG, file=sys.stderr)
    return 1


if __name__ == "__main__":
    sys.exit(main())
