#!/usr/bin/env python3
"""Regenerate the two Scp-Api-Version side-files from the catalog + docs.

Both were hand-produced one-offs until 2026-09-18; the 2026-09 spec bump
(881 version-bumped endpoints, 4 new products) made a repeatable generator
necessary. ``core.http_client`` reads them at call time:

  * ``data/api_endpoint_versions.json`` — ``services[svc]["<METHOD> <shape>"]
    = version`` where ``shape`` is the catalog ``http_path`` with every
    ``{param}`` collapsed to ``{}``. The endpoint's own CURRENT version is the
    catalog ``version`` (the docs' current page for that endpoint), which is
    the 1st source for the pin (product pins 406 on lagging methods).
  * ``data/api_versions.json`` — ``products[svc] = version`` from the docs'
    "API version" page (``/apireference/api-common/version/``, display names
    mapped to service codes via the file's own ``display_names`` map; new
    products are added to that map here), falling back to the max catalog
    version of the service when the page does not list it. ``supported``
    (older still-accepted versions) cannot be derived, so it is carried over.

Usage:  python -m spec.refresh_versions [--no-fetch]
"""
from __future__ import annotations

import html
import json
import re
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CATALOG = ROOT / "data" / "api_catalog.json"
EP_OUT = ROOT / "data" / "api_endpoint_versions.json"
PRODUCTS_OUT = ROOT / "data" / "api_versions.json"
VERSION_PAGE = "https://docs.e.samsungsdscloud.com/apireference/api-common/version/"

# display names the docs page uses for products that joined after the map was
# first written (2026-07-15). Extend here when a new product appears unmapped.
EXTRA_DISPLAY_NAMES = {
    "messagehub": "Message Hub",
    "resourceoptimizer": "Resource Optimizer",
    "costnavigator": "Cost Navigator",
    "cnapp": "CNAPP",
}
_NAME_VER_RE = re.compile(r"([A-Za-z][A-Za-z0-9&()/. \-]*?)\s+v(\d+\.\d+)\b")


def _vkey(v: str) -> tuple:
    try:
        return tuple(int(p) for p in str(v).split("."))
    except ValueError:
        return (0,)


def endpoint_versions(catalog: list[dict]) -> dict:
    services: dict[str, dict[str, str]] = {}
    for e in catalog:
        if not (e.get("method") and e.get("http_path") and e.get("version")):
            continue
        shape = re.sub(r"\{[^}]+\}", "{}", e["http_path"])
        services.setdefault(e["service"], {})[f"{e['method'].upper()} {shape}"] = str(e["version"])
    return {
        "generated_from": "data/api_catalog.json (endpoint CURRENT version per docs page; "
                          "regenerated by spec.refresh_versions)",
        "note": "엔드포인트별 지원 버전 — Scp-Api-Version 핀의 1차 소스 (제품 최신과 다른 "
                "메서드가 있다: 예 scf metrics 1.3 vs 제품 1.4 → 제품 핀은 406 NoSuchVersion). "
                "제품 핀(api_versions.json)은 폴백.",
        "services": {s: dict(sorted(m.items())) for s, m in sorted(services.items())},
    }


def parse_version_page(text: str) -> dict[str, str]:
    """``{display name: version}`` from the rendered page text."""
    t = re.sub(r"<script.*?</script>|<style.*?</style>", " ", text, flags=re.S)
    t = html.unescape(re.sub(r"<[^>]+>", " ", t))
    t = re.sub(r"\s+", " ", t)
    out: dict[str, str] = {}
    for m in _NAME_VER_RE.finditer(t):
        name = m.group(1).strip()
        # the regex is greedy-left across the flattened text: keep the last
        # 1–4 words before the version as the product name (names never exceed 4)
        words = name.split()
        for n in range(min(4, len(words)), 0, -1):
            cand = " ".join(words[-n:])
            if cand:
                out.setdefault(cand, m.group(2))
    return out


def products(catalog: list[dict], page_versions: dict[str, str] | None, existing: dict) -> dict:
    display = dict(existing.get("display_names") or {})
    display.update(EXTRA_DISPLAY_NAMES)
    by_name = {v: k for k, v in display.items()}
    svcs = sorted({e["service"] for e in catalog})
    cat_max = {}
    for e in catalog:
        if e.get("version"):
            cat_max[e["service"]] = max(cat_max.get(e["service"], "0"), str(e["version"]), key=_vkey)
    prod: dict[str, str] = {}
    source: dict[str, str] = {}
    for svc in svcs:
        name = display.get(svc)
        if page_versions and name and name in page_versions:
            prod[svc] = page_versions[name]; source[svc] = "version-page"
        elif svc in cat_max:
            prod[svc] = cat_max[svc]; source[svc] = "catalog-max"
    unmapped = sorted(n for n in (page_versions or {}) if n not in by_name)
    return {
        "fetched_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "source": VERSION_PAGE,
        "header": existing.get("header", "Scp-Api-Version"),
        "value_format": existing.get("value_format", "{product} {version}"),
        "products": prod,
        "product_version_source": source,
        "supported": existing.get("supported") or {},
        "display_names": {s: display[s] for s in sorted(display) if s in prod or s in display},
        "unmapped_display_names": [{"display_name": n, "version": page_versions[n]} for n in unmapped
                                   if page_versions and not re.search(r"\d", n)][:40],
    }


def main(argv=None) -> int:
    import argparse
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--no-fetch", action="store_true", help="skip the version page (catalog-max only)")
    args = ap.parse_args(argv)
    catalog = json.loads(CATALOG.read_text(encoding="utf-8"))
    EP_OUT.write_text(json.dumps(endpoint_versions(catalog), indent=2, ensure_ascii=False) + "\n",
                      encoding="utf-8")
    ep = json.loads(EP_OUT.read_text(encoding="utf-8"))["services"]
    print(f"endpoint versions: {sum(len(v) for v in ep.values())} entries / {len(ep)} services -> {EP_OUT}")
    page = None
    if not args.no_fetch:
        try:
            from spec.extract_catalog import fetch
            page = parse_version_page(fetch(VERSION_PAGE).decode("utf-8", "replace"))
            print(f"version page: {len(page)} name→version pairs")
        except Exception as exc:  # noqa: BLE001 — fall back to catalog-max
            print(f"version page unavailable ({exc}); using catalog max versions")
    existing = json.loads(PRODUCTS_OUT.read_text(encoding="utf-8")) if PRODUCTS_OUT.exists() else {}
    out = products(catalog, page, existing)
    PRODUCTS_OUT.write_text(json.dumps(out, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    src = out["product_version_source"]
    print(f"products: {len(out['products'])} (version-page {sum(1 for s in src.values() if s == 'version-page')}, "
          f"catalog-max {sum(1 for s in src.values() if s == 'catalog-max')}) -> {PRODUCTS_OUT}")
    changed = {s: (existing.get('products', {}).get(s), v) for s, v in out['products'].items()
               if existing.get('products', {}).get(s) != v}
    print(f"product version changes: {len(changed)}")
    for s, (o, n) in sorted(changed.items()):
        print(f"  {s}: {o} -> {n} ({src[s]})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
