#!/usr/bin/env python3
"""Emit overlay data the unified console (console.html) layers on the shared DAG.

From reports/results/observations.jsonl, aggregate by service (the first two
segments of each observation's endpoint_key = "<category>/<service>/<name>"):

  data/results.js  -> window.RESULTS {generated_from, run, summary, perService}
  data/context.js  -> window.CTX {env, suite, sha, time, mode}

Generate the observations first if missing:
    PYTHONPATH=. python3 -m tools.sample_data
Then run from repo root:
    PYTHONPATH=. python3 poc/scenario-viz/build_overlays.py
"""
import json
import subprocess
import time
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OBS = ROOT / "reports" / "results" / "observations.jsonl"
OUT_DIR = Path(__file__).resolve().parent / "data"
OUT_RESULTS = OUT_DIR / "results.js"
OUT_CTX = OUT_DIR / "context.js"

# C3 (cov_op) health thresholds: covered endpoints that returned OK (no fail).
C3_HIGH = 80.0   # green  >=
C3_MID = 50.0    # amber  >=  ; below = red


def short_sha():
    try:
        out = subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"],
            cwd=ROOT, capture_output=True, text=True, timeout=5,
        )
        sha = out.stdout.strip()
        return sha or "sample"
    except Exception:
        return "sample"


def main():
    if not OBS.exists():
        raise SystemExit(
            f"missing {OBS} — generate it first: PYTHONPATH=. python3 -m tools.sample_data"
        )

    per = defaultdict(lambda: {"total": 0, "ok": 0, "soft": 0, "fail": 0,
                               "covered": 0})
    run = "sample"
    overall = {"total": 0, "ok": 0, "soft": 0, "fail": 0, "covered": 0}

    for line in OBS.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line:
            continue
        o = json.loads(line)
        run = o.get("run", run)
        key = o.get("endpoint_key", "")
        parts = key.split("/")
        if len(parts) < 3:
            continue
        svc = parts[0] + "/" + parts[1]
        cat = o.get("category", "ok")
        rec = per[svc]
        rec["total"] += 1
        overall["total"] += 1
        if cat in ("ok", "soft", "fail"):
            rec[cat] += 1
            overall[cat] += 1
        # an endpoint is "covered" if we exercised it (any observation)
        rec["covered"] += 1
        overall["covered"] += 1

    def c3(rec):
        # C3 = cov_op success rate: of covered ops, fraction that did not fail.
        cov = rec["covered"]
        if not cov:
            return 0.0
        return round(100.0 * (rec["ok"] + rec["soft"]) / cov, 1)

    per_service = {}
    for svc, rec in sorted(per.items()):
        per_service[svc] = {
            "total": rec["total"], "ok": rec["ok"], "soft": rec["soft"],
            "fail": rec["fail"], "covered": rec["covered"], "c3_pct": c3(rec),
        }

    summary = {
        "total": overall["total"], "ok": overall["ok"], "soft": overall["soft"],
        "fail": overall["fail"], "covered": overall["covered"],
        "c3_pct": c3(overall), "service_count": len(per_service),
        "regression_count": sum(1 for r in per_service.values() if r["fail"] > 0),
    }

    payload = {
        "generated_from": "reports/results/observations.jsonl",
        "run": run,
        "thresholds": {"high": C3_HIGH, "mid": C3_MID},
        "summary": summary,
        "perService": per_service,
    }
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    js = "// AUTO-GENERATED by poc/scenario-viz/build_overlays.py — do not hand-edit.\n"
    js += "window.RESULTS = " + json.dumps(payload, ensure_ascii=False, indent=1) + ";\n"
    OUT_RESULTS.write_text(js, encoding="utf-8")

    ctx = {
        "env": "stage",
        "suite": "full",
        "sha": short_sha(),
        "time": datetime.now(timezone.utc).replace(microsecond=0).isoformat(),
        "mode": "SNAPSHOT",
    }
    cjs = "// AUTO-GENERATED by poc/scenario-viz/build_overlays.py — do not hand-edit.\n"
    cjs += "window.CTX = " + json.dumps(ctx, ensure_ascii=False) + ";\n"
    OUT_CTX.write_text(cjs, encoding="utf-8")

    print(
        f"wrote results.js ({len(per_service)} services, {summary['total']} obs, "
        f"C3 {summary['c3_pct']}%, ok/soft/fail "
        f"{summary['ok']}/{summary['soft']}/{summary['fail']}, "
        f"{summary['regression_count']} services w/ fail) + context.js "
        f"(env={ctx['env']} suite={ctx['suite']} sha={ctx['sha']} {ctx['mode']})"
    )


if __name__ == "__main__":
    main()
