#!/usr/bin/env python3
"""Extract the M5 resource-task model into a self-contained JS data file the
PoC pages embed (no fetch() so it works over file://).

Mirrors regression/scenarios/composer.load_model + _norm_requires keying
(global node_id namespace). Run from repo root:

    python3 poc/scenario-viz/build_data.py
"""
import glob
import json
import os
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[2]
RES = ROOT / "knowledge" / "formal" / "resources"
OUT = Path(__file__).resolve().parent / "data" / "model.js"

CAT_ABBR = {
    "networking": "nw", "compute": "cp", "storage": "st", "database": "db",
    "security": "sec", "management": "mg", "container": "ct", "ai-ml": "ai",
    "data-analytics": "da", "application-service": "ap", "devops-tools": "dt",
    "financial-management": "fm", "platform": "pf",
}


def norm_requires(task):
    and_deps, groups, creds = [], [], []
    for entry in task.get("requires") or []:
        if isinstance(entry, str):
            and_deps.append({"ref": entry, "count": 1})
        elif isinstance(entry, dict) and "one_of" in entry:
            branches = []
            for b in entry["one_of"]:
                branches.append(b if isinstance(b, str) else b.get("ref"))
            groups.append({"bind": entry.get("bind"), "branches": branches})
        elif isinstance(entry, dict) and "credential" in entry:
            creds.append(str(entry["credential"]))
        elif isinstance(entry, dict) and "ref" in entry:
            and_deps.append({"ref": entry["ref"], "count": int(entry.get("count", 1))})
    return and_deps, groups, creds


def main():
    groups_meta = {}
    gpath = RES / "_groups.yaml"
    if gpath.exists():
        gd = yaml.safe_load(gpath.read_text()) or {}
        groups_meta = gd.get("groups", {}) or {}

    nodes = {}
    for path in sorted(RES.glob("*.yaml")):
        if path.name.startswith("_"):
            continue
        data = yaml.safe_load(path.read_text()) or {}
        for nid, task in (data.get("resources") or {}).items():
            if not isinstance(task, dict):
                continue
            service = task.get("service", "")
            cat = service.split("/")[0] if "/" in service else path.name.split("__")[0]
            and_deps, groups, creds = norm_requires(task)
            create = task.get("create") or {}
            opts = (create.get("options") or {})
            opt_list = []
            for oname, ospec in opts.items():
                if not isinstance(ospec, dict):
                    opt_list.append({"name": oname, "type": "?", "required": False})
                    continue
                opt_list.append({
                    "name": oname,
                    "type": ospec.get("type", "?"),
                    "required": bool(ospec.get("required", False)),
                    "values": ospec.get("values"),
                    "vary": bool(ospec.get("vary", False)),
                    "ref_target": ospec.get("target") if ospec.get("type") == "ref" else None,
                })
            code = task.get("code") or ""
            group = task.get("group") or ("-".join(code.split("-")[:2]) if code else cat)
            ready = task.get("ready") or {}
            nodes[nid] = {
                "id": nid,
                "code": code,
                "service": service,
                "category": cat,
                "group": group,
                "group_label": (groups_meta.get(group) or {}).get("label", group),
                "provenance": task.get("provenance", "?"),
                "heavy": bool(task.get("heavy", False)),
                "adopt": task.get("adopt"),
                "quota": task.get("quota"),
                "endpoint": create.get("endpoint", ""),
                "and": and_deps,
                "one_of": groups,
                "creds": creds,
                "options": opt_list,
                "ready_timeout": ready.get("timeout"),
                "verify_n": len(task.get("verify") or []),
                "has_delete": bool(task.get("delete")),
            }

    # group meta for the UI (label + category), only groups actually present
    present_groups = {}
    for n in nodes.values():
        g = n["group"]
        present_groups.setdefault(g, {
            "label": (groups_meta.get(g) or {}).get("label", g),
            "category": (groups_meta.get(g) or {}).get("category", n["category"]),
        })

    payload = {
        "generated_from": "knowledge/formal/resources/*.yaml",
        "node_count": len(nodes),
        "nodes": nodes,
        "groups": present_groups,
        "cat_abbr": CAT_ABBR,
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    js = "// AUTO-GENERATED by poc/scenario-viz/build_data.py — do not hand-edit.\n"
    js += "window.MODEL = " + json.dumps(payload, ensure_ascii=False, indent=1) + ";\n"
    OUT.write_text(js, encoding="utf-8")
    val = sum(1 for n in nodes.values() if n["provenance"] == "VALIDATED")
    print(f"wrote {OUT.relative_to(ROOT)} — {len(nodes)} nodes, "
          f"{val} VALIDATED, {len(present_groups)} groups")


if __name__ == "__main__":
    main()
